/*
 * Woleet API
 *
 * Welcome to **Woleet API reference documentation**.<br> It is highly recommanded to read the chapters **[introducing Woleet API concepts](https://doc.woleet.io/reference)** before reading this documentation. 
 *
 * API version: 1.6.2
 * Contact: contact@woleet.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package woleetapi
// ReceiptSignature For proof of signature receipts only. The anchored signature.
type ReceiptSignature struct {
	// SHA256 hash (ie. the fingerprint) of the original signed data.
	SignedHash string `json:"signedHash,omitempty"`
	// X500 Distinguished Name representing the signed identity.
	SignedIdentity string `json:"signedIdentity,omitempty"`
	// Domain name of the identity issuer (ie. of the organization who verified the identity).
	SignedIssuerDomain string `json:"signedIssuerDomain,omitempty"`
	// Public key of the signee.<br> **Currently only Bitcoin addresses are supported.** 
	PubKey string `json:"pubKey,omitempty"`
	// Signature of the `signedHash` property using the public key `pubKey`, or, if any of `signedIdentity` or `signedIssuerDomain` is provided, signature of SHA256(`hashToSign` + `signedIdentity` + `signedIssuerDomain`) using the public key `pubKey`. 
	Signature string `json:"signature,omitempty"`
	// Web hook to use to verify the signee's identity.
	IdentityURL string `json:"identityURL,omitempty"`
}
