/*
 * Woleet API
 *
 * Welcome to **Woleet API reference documentation**.<br> It is highly recommanded to read the chapters **[introducing Woleet API concepts](https://doc.woleet.io/reference)** before reading this documentation. 
 *
 * API version: 1.6.2
 * Contact: contact@woleet.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package woleetapi

// Signee's identity provided as a set of X.500 attributes (see https://www.ietf.org/rfc/rfc4519.txt).
type Identity struct {
	// commonName (CN) (2.5.4.3)
	CommonName string `json:"commonName"`
	// organizationName (O) (2.5.4.10)
	Organization string `json:"organization,omitempty"`
	// organizationalUnitName (OU) (2.5.4.11)
	OrganizationalUnit string `json:"organizationalUnit,omitempty"`
	// localityName (L) (2.5.4.7)
	Locality string `json:"locality,omitempty"`
	// countryName (C) (2.5.4.6)
	Country string `json:"country,omitempty"`
}
