/*
 * Woleet API
 *
 * Welcome to **Woleet API reference documentation**.<br> It is highly recommanded to read the chapters **[introducing Woleet API concepts](https://doc.woleet.io/reference)** before reading this documentation. 
 *
 * API version: 1.6.2
 * Contact: contact@woleet.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package woleetapi

type SignatureRequestSign struct {
	// Signature of the `hashToSign` property of the signature request using the public key `pubKey`, or, if any of `signedIdentity` or `signedIssuerDomain` is provided, signature of SHA256(`hashToSign` + `signedIdentity` + `signedIssuerDomain`) using the public key `pubKey`. 
	Signature string `json:"signature"`
	// Public key used to sign. 
	PubKey string `json:"pubKey"`
	// X500 Distinguished Name representing the signed identity.<br> If set, the CN (common name) and EMAILADDRESS (email address) attributes must match the common name and email address of the authorized signee as set in the signature request. 
	SignedIdentity string `json:"signedIdentity,omitempty"`
	// Domain name of the identity issuer (ie. of the organization who verified the identity).<br> If set, the domain name of the identity URL must be included in the `signedIssuerDomain` domain name. 
	SignedIssuerDomain string `json:"signedIssuerDomain,omitempty"`
	// Web hook to use to verify the signee's identity.<br> If set, it is used in place of the `identityURL` property of the authorized signee to create the signature anchor. 
	IdentityURL string `json:"identityURL,omitempty"`
	// The type of device the authorized signee used to sign:<br> - SERVER: Woleet.ID Server or equivalent - MOBILE: Woleet.ID Mobile or equivalent - NANO: Ledger Nano S or equivalent 
	Device string `json:"device,omitempty"`
	// Secret identifier of the signee (only required if `email` was set for this signee). 
	SigneeId string `json:"signeeId,omitempty"`
	// One Time Password of the signee (only required if `requiresOTP` was set to `true` for thìs signee). 
	Otp string `json:"otp,omitempty"`
}
