/*
 * Woleet API
 *
 * Welcome to **Woleet API reference documentation**.<br> It is highly recommanded to read the chapters **[introducing Woleet API concepts](https://doc.woleet.io/reference)** before reading this documentation. 
 *
 * API version: 1.6.2
 * Contact: contact@woleet.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package woleetapi
// ReceiptProofNode struct for ReceiptProofNode
type ReceiptProofNode struct {
	Left string `json:"left,omitempty"`
	Right string `json:"right,omitempty"`
}
