/*
 * Woleet API
 *
 * Welcome to **Woleet API reference documentation**.<br> It is highly recommanded to read the chapters **[introducing Woleet API concepts](https://doc.woleet.io/v1.5.1/reference)** before reading this documentation. 
 *
 * API version: 1.5.1
 * Contact: contact@woleet.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package woleetapi

type X500Name struct {
	// Country/region
	C string `json:"C,omitempty"`
	// State or Province
	ST string `json:"ST,omitempty"`
	// Locality
	L string `json:"L,omitempty"`
	// Organization
	O string `json:"O,omitempty"`
	// Organizational Unit
	OU string `json:"OU,omitempty"`
	// Common Name
	CN string `json:"CN,omitempty"`
}
