/*
 * Woleet API
 *
 * Welcome to **Woleet API reference documentation**.<br> It is highly recommanded to read the chapters **[introducing Woleet API concepts](https://doc.woleet.io/v1.5.1/reference)** before reading this documentation. 
 *
 * API version: 1.5.1
 * Contact: contact@woleet.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package woleetapi

type Receipt struct {
	Type string `json:"type,omitempty"`
	TargetHash string `json:"targetHash,omitempty"`
	MerkleRoot string `json:"merkleRoot,omitempty"`
	Proof []ReceiptProofNode `json:"proof,omitempty"`
	Anchors []ReceiptAnchorsNode `json:"anchors,omitempty"`
	Signature ReceiptSignature `json:"signature,omitempty"`
	Header ReceiptHeader `json:"header,omitempty"`
	Target ReceiptTarget `json:"target,omitempty"`
}
