/*
 * Woleet API
 *
 * Welcome to **Woleet API reference documentation**.<br> It is highly recommanded to read the chapters **[introducing Woleet API concepts](https://doc.woleet.io/reference)** before reading this documentation. 
 *
 * API version: 1.6.2
 * Contact: contact@woleet.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package woleetapi

// Chainpoint 1.x only
type ReceiptHeader struct {
	ChainpointVersion string `json:"chainpoint_version,omitempty"`
	HashType string `json:"hash_type,omitempty"`
	MerkleRoot string `json:"merkle_root,omitempty"`
	TxId string `json:"tx_id,omitempty"`
	Timestamp int64 `json:"timestamp,omitempty"`
}
