/*
 * Woleet API
 *
 * Welcome to **Woleet API reference documentation**.<br> It is highly recommanded to read the chapters **[introducing Woleet API concepts](https://doc.woleet.io/reference)** before reading this documentation. 
 *
 * API version: 1.6.2
 * Contact: contact@woleet.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package woleetapi

type User struct {
	// User identifier. It is allocated by the platform, and so must not be provided at creation time. 
	Id string `json:"id,omitempty"`
	// Date of creation (in milliseconds since Unix epoch). 
	Created int64 `json:"created,omitempty"`
	// Date of last modification (in milliseconds since Unix epoch). 
	LastModified int64 `json:"lastModified,omitempty"`
	// Email of the user. 
	Email string `json:"email"`
	// Password of the user (it must be provided at creation time). 
	Password string `json:"password"`
	// The roles of the user:<br> - ROLE_USER: regular user<br> - ROLE_DOMAIN_ADMIN: domain administrator. 
	Roles []string `json:"roles"`
	// Object storing meta data about the user. Some property names are reserved, but properties are not limitted to the one listed here. 
	Info map[string]map[string]interface{} `json:"info"`
	// The status of the user:<br> - PENDING: the user email need to be validated<br> - APPROVED: the user can loging<br> - DISABLED: the user cannot login 
	Status string `json:"status"`
}
