/*
 * Woleet API
 *
 * Welcome to **Woleet API reference documentation**.<br> It is highly recommanded to read the chapters **[introducing Woleet API concepts](https://doc.woleet.io/v1.5.1/reference)** before reading this documentation. 
 *
 * API version: 1.5.1
 * Contact: contact@woleet.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package woleetapi

type ReceiptVerificationStatus struct {
	// Proof receipt verification status code:<br> - VERIFIED: the proof receipt is verified: the receipt format is valid, the associated Bitcoin transaction is present in the blockchain, and the receipt contains a valid cryptographic proof that its `targetHash` property is anchored into the transaction's `OP_RETURN` field. The time of the Bitcoin block into which the anchoring process occurred is returned in the `timestamp` property.<br> Any data whose SHA256 hash matches the proof receipt's `targetHash` is proven to be existent at that time and unmodified.<br> - INVALID_PROOF: the receipt's `proof` property is not a valid Merkle proof<br> - TX_NOT_FOUND: the receipt's `anchors` property does not point to a valid Bitcoin transaction<br> - TX_MISMATCH_RECEIPT: the receipt's `merkleRoot` property does not match the transaction's `OP_RETURN` field<br> - INVALID_SIGNATURE: the receipt's `signature` property is not a valid signature 
	Code string `json:"code,omitempty"`
	// Proof receipt verification status text giving more insight about verification errors.
	Text string `json:"text,omitempty"`
	// Proven timestamp of the data (for a data anchor) or of the signature (for a signature anchor).<br> This is actually the time of the Bitcoin block into which the anchoring process occurred (in milliseconds since Unix epoch).<br> Any data whose SHA256 hash equals this proof receipt's target hash property is proven to be existent at that time and unmodified. 
	Timestamp int64 `json:"timestamp,omitempty"`
	// Number of confirmations of the Bitcoin block into which the anchoring process occurred.
	Confirmations int32 `json:"confirmations,omitempty"`
	IdentityVerificationStatus IdentityVerificationStatus `json:"identityVerificationStatus,omitempty"`
}
