/*
 * Woleet API
 *
 * Welcome to **Woleet API reference documentation**.<br> It is highly recommanded to read the chapters **[introducing Woleet API concepts](https://doc.woleet.io/reference)** before reading this documentation. 
 *
 * API version: 1.6.2
 * Contact: contact@woleet.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package woleetapi

type SignatureRequest struct {
	// Signature request identifier. It is allocated by the platform, and so must not be provided at creation time. 
	Id string `json:"id,omitempty"`
	// Date of creation (in milliseconds since Unix epoch). 
	Created int64 `json:"created,omitempty"`
	// Date of last modification (in milliseconds since Unix epoch). 
	LastModified int64 `json:"lastModified,omitempty"`
	// Name of the signature request (doesn't need to be unique). 
	Name string `json:"name"`
	// `true` (or unset) if the signature anchors created in the scope of this signature request must be public (ie. discoverable by their `signedHash`).<br> `false` if they must be private (ie. not dicoverable).<br> **If this field is not set at creation time, the anchor is public by default.** 
	Public *bool `json:"public,omitempty"`
	// `true` if the signature request is suspended, or `false` (or unset) if not.<br> When suspended, no more signature can be registered before the request is resumed. 
	Suspended *bool `json:"suspended,omitempty"`
	// SHA256 hash (ie. the fingerprint) of the original data to sign. The value must be provided as an hexadecimal lowercase string. 
	HashToSign string `json:"hashToSign"`
	// List of signature anchors created in teh scope of this signature request<br> A signature anchor is created each time a new signature is registered.<br> This property is only available to the owner of the signature request. 
	Anchors []Anchor `json:"anchors,omitempty"`
	// Deadline of the signature request (in milliseconds since Unix epoch).<br> When not set, null or 0, no deadline is applied.<br> If set, signatures registered after the deadline are refused. 
	Deadline int64 `json:"deadline,omitempty"`
	// Web hook to use to verify the signee's identity.<br> If set, it is used to verify signees' identity at signature registration time. 
	IdentityURL string `json:"identityURL,omitempty"`
	// Maximum number of signatures to accept for this signature request.<br> When not set, null or 0, no maximum is applied.<br> This property and the `authorizedSignees` property are mutually exclusive.<br> This property is only available to the owner of the signature request. 
	MaxSignatures int32 `json:"maxSignatures,omitempty"`
	// List of all signees authorized to register their signature for this signature request (no duplicate is authorized).<br> When not set or null, anybody can sign the signature request.<br> If set, signatures registered by signees not in this list are rejected.<br> This property and the `maxSignatures` property are mutually exclusive.<br> This property is only available to the owner of the signature request. 
	AuthorizedSignees []AuthorizedSignee `json:"authorizedSignees,omitempty"`
}
