/*
 * Woleet API
 *
 * Welcome to **Woleet API reference documentation**.<br> It is highly recommanded to read the chapters **[introducing Woleet API concepts](https://doc.woleet.io/reference)** before reading this documentation. 
 *
 * API version: 1.6.2
 * Contact: contact@woleet.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package woleetapi

type IdentityVerificationStatus struct {
	// Identity verification status code:<br> - VERIFIED: the key is controlled by the identity server,<br> and/or the key is associated to an identity on the identity server,<br> and/or the identity is included in the anchored signature,<br> and/or the signed identity matches the one claimed by the identity server,<br> - IDENTITY_MISMATCH: the identity included in the anchored signature mismatch the identity claimed by the identity server<br> - INVALID_SIGNATURE: the identity URL returned an invalid signature (ie. the identity server failed to prove that it owns the private part of key pair)<br> - HTTP_ERROR: the identity URL returned an HTTP error 
	Code string `json:"code,omitempty"`
	// Identity verification status text (gives more insights about the verification process).
	Text string `json:"text,omitempty"`
	// Array of subjects and issuers of the certificates extracted from the identity URL's TLS certificate.
	Certificates []X509SubjectIssuer `json:"certificates,omitempty"`
	Identity Identity `json:"identity,omitempty"`
	SignedIdentity Identity `json:"signedIdentity,omitempty"`
	// Domain name of the identity issuer (ie. of the organization who verified the identity).
	SignedIssuerDomain string `json:"signedIssuerDomain,omitempty"`
}
