/*
 * Woleet API
 *
 * Welcome to **Woleet API reference documentation**.<br> It is highly recommanded to read the chapters **[introducing Woleet API concepts](https://doc.woleet.io/reference)** before reading this documentation. 
 *
 * API version: 1.7.5
 * Contact: contact@woleet.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package woleetapi
// Anchor struct for Anchor
type Anchor struct {
	// Anchor identifier. It is allocated by the platform, and so must not be provided at creation time.
	Id string `json:"id,omitempty"`
	// Date of creation (in milliseconds since Unix epoch).
	Created int64 `json:"created,omitempty"`
	// Date of last modification (in milliseconds since Unix epoch).
	LastModified int64 `json:"lastModified,omitempty"`
	// Name of the anchor (doesn't need to be unique).
	Name string `json:"name"`
	// SHA256 hash (ie. the fingerprint) of the original data to anchor.<br> The value must be provided as an hexadecimal lowercase string.<br> **This property must not be provided when creating a signature anchor: it is set at creation time to the SHA256 hash of the `signature` property provided (so the signature is what is actually anchored in this case).** 
	Hash string `json:"hash,omitempty"`
	// SHA256 hash (ie. the fingerprint) of the original signed data.<br> The value must be provided as an hexadecimal lowercase string.<br> **This property must not be provided when creating a data anchor.** 
	SignedHash string `json:"signedHash,omitempty"`
	// X500 Distinguished Name representing the signed identity.<br> **This property must not be provided when creating a data anchor.** 
	SignedIdentity string `json:"signedIdentity,omitempty"`
	// Domain name of the identity issuer (ie. of the organization who verified the identity).<br> If set, the domain name of the identity URL must be included in the `signedIssuerDomain` domain name.<br> **This property must not be provided when creating a data anchor.** 
	SignedIssuerDomain string `json:"signedIssuerDomain,omitempty"`
	// Public key of the signer.<br> **Currently only Bitcoin addresses are supported.**<br> **This property must not be provided when creating a data anchor.** 
	PubKey string `json:"pubKey,omitempty"`
	// Signature of the `signedHash` property using the public key `pubKey`, or, if any of the `signedIdentity` or `signedIssuerDomain` properties are provided, signature of SHA256(`hashToSign` + `signedIdentity` + `signedIssuerDomain`) using the public key `pubKey`.<br> **Only Bitcoin signatures are currently supported.**<br> **This property must not be provided when creating a data anchor.** 
	Signature string `json:"signature,omitempty"`
	// Web hook of the identity server to use to verify the signer's identity.<br> This URL allows to retrieve the identity associated to the public key `pubKey`. It can also be used to verify that the identity server (itself identified by the TLS certificate of the URL) controls the key used to sign (ie. owns the private part of the key pair) by requesting it to sign some random data.<br> This URL MUST use an HTTPS scheme with a valid and non expired TLS certificate.<br> This URL MUST implement the following GET operation:<br> Query parameters:<br> - `pubKey`: the public key to be verified - mandatory<br> - `leftData`: the left part of the data to be signed (generated randomly by the caller) - if set, the identity server MAY provide a `signature`<br> Output:<br> A JSON object with: - `rightData`: the right part of the data signed (generated randomly by the identity server) - optional<br> - `signature`: the signature of the string `leftData` + `rightData` using the public key `pubKey` - optional<br> - `identity`: the X500 identity associated to the key claimed by the identity server - optional<br> - `key`: additional information about the key - optional<br> If `identity` is not provided, `signature` and `rightData` MUST be provided: in such a case the identity of the signer can be extracted from the TLS certificate. 
	IdentityURL string `json:"identityURL,omitempty"`
	// `true` (or unset) if the anchor is public (ie. discoverable by its `hash` or `signedHash`).<br> `false` if it must be private (ie. not discoverable).<br> **If this property is not set, the anchor is public by default.** 
	Public *bool `json:"public,omitempty"`
	// `true` if the proof receipt must be sent by email once available, or `false` (or unset) if not. 
	NotifyByEmail *bool `json:"notifyByEmail,omitempty"`
	// Set of tags associated to the anchor. There is no restriction on tag names, except they cannot contain spaces.<br> Tags are aimed at classifying and searching anchors. 
	Tags []string `json:"tags,omitempty"`
	// A set of variables (key/values pairs) to store with the anchor and giving additional information about the anchored data.<br> Values must be of type null, boolean, string or number: nested JSON objects are not allowed. 
	Metadata map[string]interface{} `json:"metadata,omitempty"`
	// Web hook to be called by the platform whenever the anchor status changes:<br> the platform does a POST request on this URL with the anchor as a JSON object in the request body.<br> Verifying the authenticity of the callback can be done by checking the HMAC-SHA1 signature of the request body provided by Woleet in the `x-woleet-signature` header.<br> Please refer to the <a target=\"_blank\" href=\"https://doc.woleet.io/reference#using-callbacks\">documentation</a> for more details. 
	CallbackURL string `json:"callbackURL,omitempty"`
	// Status of the anchor:<br> - WAIT: waiting to be processed by the platform (the proof receipt is not yet available for download)<br> - NEW: waiting to be sent to the blockchain (the proof receipt is not yet available for download)<br> - SENT: sent to the blockchain (the proof receipt can be downloaded)<br> - CONFIRMED: confirmed at least 6 times by the blockchain (the proof receipt can be verified) 
	Status string `json:"status,omitempty"`
	// Proven timestamp of the data (for a data anchor) or of the signature (for a signature anchor).<br> This is actually the time of the Bitcoin block into which the anchoring process occurred (in milliseconds since Unix epoch).<br> Any data whose SHA256 hash equals this anchor's hash is proven to exist at that time and has not been modified since.<br> This property is set when the first confirmation of the Bitcoin block occurs. Once set, the associated proof receipt can be verified (without having to wait for 6 confirmations). 
	Timestamp int64 `json:"timestamp,omitempty"`
	// Number of confirmations of the Bitcoin block into which the anchoring process occurred.<br> This property is set when the first confirmation of the Bitcoin block occurs, and removed once the block is confirmed at least 6 times. 
	Confirmations int32 `json:"confirmations,omitempty"`
	// Identifier of the Bitcoin transaction where the anchoring occurred.
	TxId string `json:"txId,omitempty"`
}
