/*
 * Woleet API
 *
 * Welcome to **Woleet API reference documentation**.<br> It is highly recommanded to read the chapters **[introducing Woleet API concepts](https://doc.woleet.io/reference)** before reading this documentation. 
 *
 * API version: 1.6.2
 * Contact: contact@woleet.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package woleetapi
// ReceiptTarget Chainpoint 1.x only
type ReceiptTarget struct {
	TargetHash string `json:"target_hash,omitempty"`
	TargetProof []ReceiptTargetProofNode `json:"target_proof,omitempty"`
}
