/*
 * Woleet API
 *
 * Welcome to **Woleet API reference documentation**.<br> It is highly recommanded to read the chapters **[introducing Woleet API concepts](https://doc.woleet.io/v1.5.1/reference)** before reading this documentation. 
 *
 * API version: 1.5.1
 * Contact: contact@woleet.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package woleetapi

// For Chainpoint 1.x receipts only
type ReceiptTarget struct {
	TargetHash string `json:"target_hash,omitempty"`
	TargetProof []ReceiptTargetProofNode `json:"target_proof,omitempty"`
}
