/*
 * Woleet API
 *
 * Welcome to **Woleet API reference documentation**.<br> It is highly recommanded to read the chapters **[introducing Woleet API concepts](https://doc.woleet.io/reference)** before reading this documentation. 
 *
 * API version: 1.6.2
 * Contact: contact@woleet.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package woleetapi

// A Chainpoint 1.x or 2.x proof receipt
type Receipt struct {
	// Chainpoint 2.x only. Type of Chainpoint 2.x receipt.
	Type string `json:"type,omitempty"`
	// Chainpoint 2.x only. SHA256 hash of the proven data or signature.
	TargetHash string `json:"targetHash,omitempty"`
	// Chainpoint 2.x only. Root of the Merkle tree.
	MerkleRoot string `json:"merkleRoot,omitempty"`
	// Chainpoint 2.x only. Merkle proof: path from `targetHash` to `merkleRoot` in the Merkle tree. 
	Proof []ReceiptProofNode `json:"proof,omitempty"`
	// Chainpoint 2.x only. List of sources where the root of the Merkle proof is anchored.
	Anchors []ReceiptAnchorsNode `json:"anchors,omitempty"`
	Signature ReceiptSignature `json:"signature,omitempty"`
	Header ReceiptHeader `json:"header,omitempty"`
	Target ReceiptTarget `json:"target,omitempty"`
}
