# .goreleaser.yml
# Build customization
builds:
  - main: main.go
    binary: woleet-cli
    goos:
      - darwin
      - linux
    goarch:
      - amd64

# Archive customization
archive:
  format: tar.gz
  replacements:
    amd64: x86_64
  files:
    - none*
