/*
 * Woleet API
 *
 * Welcome to **Woleet API reference documentation**.<br> It is highly recommanded to read the chapters **[introducing Woleet API concepts](https://doc.woleet.io/v1.5.1/reference)** before reading this documentation.
 *
 * OpenAPI spec version: 1.5.1
 * Contact: contact@woleet.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package models

type Anchor struct {

	// Anchor identifier. It is allocated by the platform, and so must not be provided at creation time.
	Id string `json:"id,omitempty"`

	// Date of creation (in milliseconds since Unix epoch).
	Created int64 `json:"created,omitempty"`

	// Date of last modification (in milliseconds since Unix epoch).
	LastModified int64 `json:"lastModified,omitempty"`

	// Name of the anchor (doesn't need to be unique).
	Name string `json:"name"`

	// SHA256 hash (ie. the fingerprint) of the original data to anchor.<br> **This property must not be provided when creating a signature anchor: it is set at creation time to the SHA256 hash of the `signature` property provided (so the signature is what is actually anchored in this case).**
	Hash string `json:"hash,omitempty"`

	// SHA256 hash (ie. the fingerprint) of the original data to sign.<br> **This property must not be provided when creating a data anchor.**
	SignedHash string `json:"signedHash,omitempty"`

	// Public key of the signee.<br> **Currently only Bitcoin addresses are supported.**<br> **This property must not be provided when creating a data anchor.**
	PubKey string `json:"pubKey,omitempty"`

	// Signature of the `signedHash` property using the public key stored in the `pubKey` property.<br> **Only Bitcoin signatures are currently supported.**<br> **This property must not be provided when creating a data anchor.**
	Signature string `json:"signature,omitempty"`

	// Web hook to use to verify the signee's identity.<br> Calling this URL allows to verify that the owner of the URL (identified by the associated TLS certificate) also owns the public key used to produce the signature, by asking the URL to sign some random data.<br> This URL must use an HTTPS scheme with a valid and non expired TLS certificate.<br> This URL must implement the following GET operation:<br> input:<br> - `pubKey`: the public key to be verified<br> - `leftData`: the left part of the random data to be signed (generated by the caller)<br> output:<br> - `rightData`: the right part of the random data signed (generated by the callee)<br> - `signature`: the signature of the string `leftData` + `rightData` produced using the public key `pubKey`
	IdentityURL string `json:"identityURL,omitempty"`

	// `true` (or unset) if the anchor is public. `false` if the anchor is private.<br> **If this field is not set at creation time, the anchor is public by default.**
	Public *bool `json:"public,omitempty"`

	// `true` if the proof receipt must be sent by email once available, or `false` (or unset) if not.
	NotifyByEmail *bool `json:"notifyByEmail,omitempty"`

	// Set of tags associated to the anchor. There is no restriction on tag names, except they cannot contain spaces.<br> Tags are aimed at classifying and searching anchors.
	Tags []string `json:"tags,omitempty"`

	// A JSON object containing a set of key/values to store with the anchor and giving additional information about the anchored data.<br> Values must be of type null, boolean, string or number: nested JSON objects are not allowed.<br> ex: { title: 'Ubik', author: 'Philip K. Dick', read: true, rank: 10.0, coauthor: null }
	Metadata interface{} `json:"metadata,omitempty"`

	// Web hook to be called by the platform whenever the anchor status change: the platform does a POST request on this URL with the anchor as a JSON object in the request body. Verifying the authenticity of the callback can be done by checking the HMAC-SHA1 signature of the request body provided by Woleet in the `x-woleet-signature` header. For more information see the <a target=\"_blank\" href=\"https://doc.woleet.io/v1.5.1/reference#verifying-callback-authenticity\">documentation</a>.
	CallbackURL string `json:"callbackURL,omitempty"`

	// Status of the anchor:<br> - WAIT: waiting to be processed by the platform (the proof receipt is not yet available for download)<br> - NEW: waiting to be sent to the blockchain (the proof receipt is not yet available for download)<br> - SENT: sent to the blockchain (the proof receipt is available for download)<br> - CONFIRMED: confirmed at least 6 times by the blockchain (the proof receipt is available for download)<br>
	Status string `json:"status,omitempty"`

	// Proven timestamp of the data.<br> This is actually the time of the Bitcoin block into which the anchoring process occurred (in milliseconds since Unix epoch).<br> Any data whose SHA256 hash equals this anchor's hash is proven to be existent at that time and unmodified.<br> This field is set when the first confirmation of the Bitcoin block occurs.<br>
	Timestamp int64 `json:"timestamp,omitempty"`

	// Number of confirmations of the Bitcoin block into which the anchoring process occurred.<br> This field is set when the first confirmation of the Bitcoin block occurs, and removed when the block is confirmed.<br>
	Confirmations int32 `json:"confirmations,omitempty"`

	// Identifier of the Bitcoin transaction where the anchoring occurred.
	TxId string `json:"txId,omitempty"`
}
