/* 
 * Woleet API
 *
 * Welcome to **Woleet API reference documentation**.<br> It is highly recommanded to read the chapters **[introducing Woleet API concepts](https://doc.woleet.io/v1.5.1/reference)** before reading this documentation. 
 *
 * OpenAPI spec version: 1.5.1
 * Contact: contact@woleet.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package models

type AuthorizedSignee struct {

	// The public key of the authorized signee.
	PubKey string `json:"pubKey,omitempty"`

	// `true` if this signee's signature is mandatory.<br> This property is informative, it is not used by the platform. 
	Required bool `json:"required,omitempty"`
}
