/* 
 * Woleet API
 *
 * Welcome to **Woleet API reference documentation**.<br> It is highly recommanded to read the chapters **[introducing Woleet API concepts](https://doc.woleet.io/v1.5.1/reference)** before reading this documentation. 
 *
 * OpenAPI spec version: 1.5.1
 * Contact: contact@woleet.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package models

type Receipt struct {

	Type_ string `json:"type,omitempty"`

	TargetHash string `json:"targetHash,omitempty"`

	MerkleRoot string `json:"merkleRoot,omitempty"`

	Proof []ReceiptProofNode `json:"proof,omitempty"`

	Anchors []ReceiptAnchorsNode `json:"anchors,omitempty"`

	Signature ReceiptSignature `json:"signature,omitempty"`

	Header ReceiptHeader `json:"header,omitempty"`

	Target ReceiptTarget `json:"target,omitempty"`
}
