/* 
 * Woleet API
 *
 * Welcome to **Woleet API reference documentation**.<br> It is highly recommanded to read the chapters **[introducing Woleet API concepts](https://doc.woleet.io/v1.5.1/reference)** before reading this documentation. 
 *
 * OpenAPI spec version: 1.5.1
 * Contact: contact@woleet.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package models

type SignatureRequestSign struct {

	// Signature of the `hashToSign` property of the signature request using the public key stored in the `pubKey` property. 
	Signature string `json:"signature,omitempty"`

	// Public key of the signee. 
	PubKey string `json:"pubKey,omitempty"`
}
