/* 
 * Woleet API
 *
 * Welcome to **Woleet API reference documentation**.<br> It is highly recommanded to read the chapters **[introducing Woleet API concepts](https://doc.woleet.io/v1.5.1/reference)** before reading this documentation. 
 *
 * OpenAPI spec version: 1.5.1
 * Contact: contact@woleet.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package models

type SignatureRequest struct {

	// Signature request identifier. It is allocated by the platform, and so must not be provided at creation time. 
	Id string `json:"id,omitempty"`

	// Date of creation (in milliseconds since Unix epoch). 
	Created int64 `json:"created,omitempty"`

	// Date of last modification (in milliseconds since Unix epoch). 
	LastModified int64 `json:"lastModified,omitempty"`

	// Name of the signature request (doesn't need to be unique). 
	Name string `json:"name"`

	// `true` if the signature request is suspended, or `false` (or unset) if not.<br> When suspended, no more signature can be registered before the request is resumed. 
	Suspended bool `json:"suspended,omitempty"`

	// SHA256 hash (ie. the fingerprint) of the original data to sign. 
	HashToSign string `json:"hashToSign"`

	// List of signature anchors created for this signature request.<br> This property is only available to the owner of the signature request. 
	Anchors []Anchor `json:"anchors,omitempty"`

	// Deadline of the signature request (in milliseconds since Unix epoch).<br> When not set, null or 0, no deadline is applied.<br> If set, signatures registered after the deadline are refused. 
	Deadline int64 `json:"deadline,omitempty"`

	// Maximum number of signatures to accept for this signature request.<br> When not set, null or 0, no maximum is applied.<br> If set, signatures coming from signees not in this list are refused.<br> This property and the `authorizedSignees` property are mutually exclusive.<br> This property is only available to the owner of the signature request. 
	MaxSignatures int32 `json:"maxSignatures,omitempty"`

	// List of public keys of all signees authorized to register their signature for this signature request (no duplicate is authorized).<br> **Currently only Bitcoin addresses are supported.**<br> When not set or null, anybody can sign the signature request.<br> If set, signatures from public keys not in this list are rejected.<br> This property and the `maxSignatures` property are mutually exclusive.<br> This property is only available to the owner of the signature request. 
	AuthorizedSignees []AuthorizedSignee `json:"authorizedSignees,omitempty"`
}
