/* 
 * Woleet backend kit API
 *
 * The Woleet backend kit API, as exposed by Woleet backend kit's NodeJS server, allows:  - **your backend** (and only yours) to sign some data using its bitcoin identity (as generated during backend kit installation)  - **anyone** to verify that your backend effectively owns its claimed bitcoin address 
 *
 * OpenAPI spec version: 1.0.0
 * Contact: contact@woleet.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package modelsBackendkit

type ErrorError struct {

	// the statusCode matches the returned http status code
	StatusCode int32 `json:"statusCode,omitempty"`

	Message string `json:"message,omitempty"`

	Type_ string `json:"type,omitempty"`
}
