/*
 * Woleet.ID Server
 *
 * This is Woleet.ID Server API documentation.
 *
 * API version: 1.2.0
 * Contact: contact@woleet.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package idserver
// UserRoleEnum : User role.
type UserRoleEnum string

// List of UserRoleEnum
const (
	USERROLEENUM_USER UserRoleEnum = "user"
	USERROLEENUM_ADMIN UserRoleEnum = "admin"
)