/*
 * Woleet.ID Server
 *
 * This is Woleet.ID Server API documentation.
 *
 * API version: 1.2.0
 * Contact: contact@woleet.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package idserver
// KeyHolderEnum : The entity who hold the private key.
type KeyHolderEnum string

// List of KeyHolderEnum
const (
	KeyHolderSERVER KeyHolderEnum = "server"
	KeyHolderUSER KeyHolderEnum = "user"
)