/*
 * Woleet.ID Server
 *
 * This is Woleet.ID Server API documentation.
 *
 * API version: 1.2.0
 * Contact: contact@woleet.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package idserver

type UserPostAllOf struct {
	// If true create a key holded by the server when this user is created.
	CreateDefaultKey *bool `json:"createDefaultKey"`
}
