/*
 * Woleet.ID Server
 *
 * This is Woleet.ID Server API documentation.
 *
 * API version: 1.2.5
 * Contact: contact@woleet.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package idserver
// KeyHolderEnum The type of entity holding the private key.<br> - `server`: the server (Woleet.ID Server or equivalent)<br> - `user`: the user (eg. by using a Ledger Nano S or Woleet.ID Mobile or equivalent) 
type KeyHolderEnum string

// List of KeyHolderEnum
const (
	KEYHOLDERENUM_SERVER KeyHolderEnum = "server"
	KEYHOLDERENUM_USER KeyHolderEnum = "user"
)
