/*
 * Woleet.ID Server
 *
 * This is Woleet.ID Server API documentation.
 *
 * API version: 1.2.0
 * Contact: contact@woleet.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package idserver
// KeyTypeEnum : Key type.
type KeyTypeEnum string

// List of KeyTypeEnum
const (
	KEYTYPEENUM_BIP39 KeyTypeEnum = "bip39"
)