/*
 * Woleet.ID Server
 *
 * This is Woleet.ID Server API documentation.
 *
 * API version: 1.2.0
 * Contact: contact@woleet.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package idserver

// User identity provided as a set of X500 Distinguished Name attributes (see https://www.ietf.org/rfc/rfc4519.txt).
type Identity struct {
	// Common name (CN) (2.5.4.3)
	CommonName string `json:"commonName"`
	// Email Address (EMAILADDRESS) (1.2.840.113549.1.9.1)
	EmailAddress string `json:"emailAddress,omitempty"`
	// Organization name (O) (2.5.4.10)
	Organization string `json:"organization,omitempty"`
	// Organizational unit name (OU) (2.5.4.11)
	OrganizationalUnit string `json:"organizationalUnit,omitempty"`
	// Locality name (L) (2.5.4.7)
	Locality string `json:"locality,omitempty"`
	// Country code (C) (2.5.4.6)
	Country string `json:"country,omitempty"`
}
