/*
 * Woleet.ID Server
 *
 * This is Woleet.ID Server API documentation.
 *
 * API version: 1.2.0
 * Contact: contact@woleet.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package idserver
// ConfigDisco struct for ConfigDisco
type ConfigDisco struct {
	// Public URL of the `/identity` endpoint (ie. the URL that anyone can use to get the identity associated with a public key). 
	IdentityURL string `json:"identityURL,omitempty"`
}
