/*
 * Woleet.ID Server
 *
 * This is Woleet.ID Server API documentation.
 *
 * API version: 1.2.5
 * Contact: contact@woleet.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package idserver
// UserStatusEnum User status:<br> - `active`: the user is active: he can use his keys to sign<br> - `blocked`: the user is blocked: he cannot use his keys to sign 
type UserStatusEnum string

// List of UserStatusEnum
const (
	USERSTATUSENUM_ACTIVE UserStatusEnum = "active"
	USERSTATUSENUM_BLOCKED UserStatusEnum = "blocked"
)
