/*
 * Woleet.ID Server
 *
 * This is Woleet.ID Server API documentation.
 *
 * API version: 1.0.4
 * Contact: contact@woleet.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package idserver

// User identity provided as a set of X.500 attributes (see https://www.ietf.org/rfc/rfc4519.txt).
type Identity struct {
	// commonName (CN) (2.5.4.3)
	CommonName string `json:"commonName"`
	// organizationName (O) (2.5.4.10)
	Organization string `json:"organization,omitempty"`
	// organizationalUnitName (OU) (2.5.4.11)
	OrganizationalUnit string `json:"organizationalUnit,omitempty"`
	// localityName (L) (2.5.4.7)
	Locality string `json:"locality,omitempty"`
	// countryName (C) (2.5.4.6)
	Country string `json:"country,omitempty"`
}
