/*
 * Woleet.ID Server
 *
 * This is Woleet.ID Server API documentation.
 *
 * API version: 1.2.5
 * Contact: contact@woleet.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package idserver
// KeyTypeEnum The type of the key (only `bip39` is supported).<br> - `bip39`: Bitcoin BIP39 
type KeyTypeEnum string

// List of KeyTypeEnum
const (
	KEYTYPEENUM_BIP39 KeyTypeEnum = "bip39"
)
