/*
 * Woleet.ID Server
 *
 * This is Woleet.ID Server API documentation.
 *
 * API version: 1.2.0
 * Contact: contact@woleet.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package idserver

type UserPut struct {
	// User identifier (allocated by the server).
	Id string `json:"id,omitempty"`
	// User email (can be used for login).
	Email string `json:"email,omitempty"`
	// User name (can be used for login).
	Username string `json:"username,omitempty"`
	// User country calling code
	CountryCallingCode string `json:"countryCallingCode,omitempty"`
	// User phone number
	Phone string `json:"phone,omitempty"`
	Status UserStatusEnum `json:"status,omitempty"`
	Role UserRoleEnum `json:"role,omitempty"`
	Identity FullIdentity `json:"identity,omitempty"`
	// User password.
	Password string `json:"password,omitempty"`
	// Identifier of the default key to use to sign for this user (cannot be the an external key).
	DefaultKeyId string `json:"defaultKeyId,omitempty"`
}
