/*
 * Woleet.ID Server
 *
 * This is Woleet.ID Server API documentation.
 *
 * API version: 1.0.4
 * Contact: contact@woleet.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package idserver

type Mnemonics struct {
	// List of mnemonic words used to recover or import a key.
	Phrase string `json:"phrase,omitempty"`
}
