/*
 * Woleet.ID Server
 *
 * This is Woleet.ID Server API documentation.
 *
 * API version: 1.2.5
 * Contact: contact@woleet.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package idserver
// UserRoleEnum User role.<br> - `user`: a user can sign using his keys<br> - `manager`: a manager can manage user and seal identities and keys<br> - `admin`: an administrator can do everything on the server 
type UserRoleEnum string

// List of UserRoleEnum
const (
	USERROLEENUM_USER UserRoleEnum = "user"
	USERROLEENUM_MANAGER UserRoleEnum = "manager"
	USERROLEENUM_ADMIN UserRoleEnum = "admin"
)
