/*
 * Woleet.ID Server
 *
 * This is Woleet.ID Server API documentation.
 *
 * API version: 1.2.0
 * Contact: contact@woleet.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package idserver
// FullIdentity struct for FullIdentity
type FullIdentity struct {
	// Common name (CN) (2.5.4.3)
	CommonName string `json:"commonName"`
	// Organization name (O) (2.5.4.10)
	Organization string `json:"organization,omitempty"`
	// Organizational unit name (OU) (2.5.4.11)
	OrganizationalUnit string `json:"organizationalUnit,omitempty"`
	// Locality name (L) (2.5.4.7)
	Locality string `json:"locality,omitempty"`
	// Country code (C) (2.5.4.6)
	Country string `json:"country,omitempty"`
	// Custom user identifier (UID) (0.9.2342.19200300.100.1.1) must be unique for each user.
	UserId string `json:"userId,omitempty"`
}
