/*
 * Woleet.ID Server
 *
 * This is Woleet.ID Server API documentation.
 *
 * API version: 1.0.4
 * Contact: contact@woleet.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package idserver

type FullIdentity struct {
	// commonName (CN) (2.5.4.3)
	CommonName string `json:"commonName"`
	// organizationName (O) (2.5.4.10)
	Organization string `json:"organization,omitempty"`
	// organizationalUnitName (OU) (2.5.4.11)
	OrganizationalUnit string `json:"organizationalUnit,omitempty"`
	// localityName (L) (2.5.4.7)
	Locality string `json:"locality,omitempty"`
	// countryName (C) (2.5.4.6)
	Country string `json:"country,omitempty"`
	// userId (UID) (0.9.2342.19200300.100.1.1) <br>The custom user identifier: it must be unique for each user. 
	UserId string `json:"userId,omitempty"`
}
