/*
 * Woleet.ID Server
 *
 * This is Woleet.ID Server API documentation.
 *
 * API version: 1.2.0
 * Contact: contact@woleet.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package idserver

type FullIdentityAllOf struct {
	// Custom user identifier (UID) (0.9.2342.19200300.100.1.1) must be unique for each user.
	UserId string `json:"userId,omitempty"`
}
