/*
 * Woleet.ID Server
 *
 * This is Woleet.ID Server API documentation.
 *
 * API version: 1.2.0
 * Contact: contact@woleet.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package idserver
// KeyStatusEnum : Key status (a `blocked` key cannot be used to sign).
type KeyStatusEnum string

// List of KeyStatusEnum
const (
	KEYSTATUSENUM_ACTIVE KeyStatusEnum = "active"
	KEYSTATUSENUM_BLOCKED KeyStatusEnum = "blocked"
	KEYSTATUSENUM_REVOKED KeyStatusEnum = "revoked"
)