/*
 * Woleet.ID Server
 *
 * This is Woleet.ID Server API documentation.
 *
 * API version: 1.2.0
 * Contact: contact@woleet.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package idserver
// KeyDeviceEnum : Key device.
type KeyDeviceEnum string

// List of KeyDeviceEnum
const (
	KeyDeviceSERVER KeyDeviceEnum = "server"
	KeyDeviceNANO KeyDeviceEnum = "nano"
	KeyDeviceMOBILE KeyDeviceEnum = "mobile"
)