/*
 * Woleet.ID Server
 *
 * This is Woleet.ID Server API documentation.
 *
 * API version: 1.2.5
 * Contact: contact@woleet.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package idserver
// KeyDeviceEnum The type of device storing the key.<br> - `server`: Woleet.ID Server or equivalent<br> - `mobile`: Woleet.ID Mobile or equivalent<br> - `nano`: Ledger Nano S or equivalent 
type KeyDeviceEnum string

// List of KeyDeviceEnum
const (
	KEYDEVICEENUM_SERVER KeyDeviceEnum = "server"
	KEYDEVICEENUM_MOBILE KeyDeviceEnum = "mobile"
	KEYDEVICEENUM_NANO KeyDeviceEnum = "nano"
)
