/*
 * Woleet.ID Server
 *
 * This is Woleet.ID Server API documentation.
 *
 * API version: 1.2.5
 * Contact: contact@woleet.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package idserver
// ConfigDisco struct for ConfigDisco
type ConfigDisco struct {
	// Public URL of the **Identity endpoint** (ie. the URL that anyone can use to get the identity associated to a public key). 
	IdentityURL string `json:"identityURL,omitempty"`
	// Public base URL of **Signature endpoints** (ie. the base URL that authorized users can use to sign and to discover other users). 
	SignatureURL string `json:"signatureURL,omitempty"`
	// Public base URL of **API endpoints** (ie. the base URL that authorized users can use to call the server API). 
	APIURL string `json:"APIURL,omitempty"`
	// API version number of this wserver instance (extraced from the swagger file). 
	APIVersion string `json:"APIVersion,omitempty"`
}
