/*
 * Woleet.ID Server
 *
 * This is Woleet.ID Server API documentation.
 *
 * API version: 1.2.0
 * Contact: contact@woleet.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package idserver

// Key information.
type Key struct {
	// Key name.
	Name string `json:"name,omitempty"`
	// Public key (bitcoin address when using BIP39 keys).
	PubKey string `json:"pubKey,omitempty"`
	Status string `json:"status,omitempty"`
	// Key expiration date (Unix ms timestamp). <br>Note that the field is not returned if the key has no expiration date. 
	Expiration int64 `json:"expiration,omitempty"`
}
